<Project>
  <ItemDefinitionGroup>
    <ClCompile>
      <ForcedIncludeFiles Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">PropsDebugX64.h</ForcedIncludeFiles>
      <ForcedIncludeFiles Condition="'$(Configuration)|$(Platform)'=='Release|x64'">PropsReleaseX64.h</ForcedIncludeFiles>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
